### ISSUE TITLE
I need help again!

### ISSUE THREAD

**Issue by NightTerror5293** [obiwac/python-minecraft-clone#66]
yo bro,
I made changes in the files,
but still am getting this problem!
pls help!
![image](https://user-images.githubusercontent.com/88367912/157065925-4217bb3f-f831-445e-9728-75bb42385528.png)

**Comment by obiwac** [comment]
Please be a bit more descriptive in your issue titles next time :smile: 

I can't really say much about that error without seeing the code, but it seems like your terrain generation in `world.py` is adding blocks which are out of range (i.e., your block types don't go beyond the ID it's adding).

I kind of do expect/assume a certain background in Python in my series, so perhaps it'd be best if you got yourself a bit more comfortable with the language before coming back to it! Otherwise, if you just want to play around with/modify the game, you can always just clone from this repo directly.

**Comment by obiwac** [comment]
Closing this issue :)
